eureka:
  client:
    serviceUrl:
      defaultZone: http://backup:7999/eureka/,http://master:7998/eureka/

server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zuul:
  routes:
    api-a:
      #以“/user-api/**”开头的Uri请求，转发到服务名为 user-service的服务
      path: /user-api/**
      serviceId: user-service