eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:12321@backup:7999/eureka/,http://admin:12321@master:7998/eureka/
server:
  port: 8761
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

#spring.sleuth.sampler.percentage为1.0,即100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest