eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:12321@backup:7999/eureka/,http://admin:12321@master:7998/eureka/

server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://118.123.16.211:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver

zipkin:
  storage:
    type: mysql

